# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDemoblazeConfirmation():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_demoblazeConfirmation(self):
    self.driver.get("https://www.demoblaze.com/")
    self.driver.set_window_size(1722, 1034)
    self.driver.find_element(By.ID, "cartur").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("Tasnim")
    self.driver.find_element(By.ID, "country").send_keys("Tunisia")
    self.driver.find_element(By.ID, "city").send_keys("Tunis")
    self.driver.find_element(By.ID, "card").click()
    self.driver.find_element(By.ID, "card").send_keys("2222")
    self.driver.find_element(By.ID, "month").click()
    self.driver.find_element(By.ID, "month").send_keys("2")
    self.driver.find_element(By.ID, "year").click()
    self.driver.find_element(By.ID, "year").send_keys("2022")
    self.driver.find_element(By.CSS_SELECTOR, "#orderModal .btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".confirm").click()
    self.driver.find_element(By.ID, "cartur").click()
  
