# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDemoblazePages():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_demoblazePages(self):
    self.driver.get("https://www.demoblaze.com/")
    self.driver.set_window_size(1722, 1034)
    self.driver.find_element(By.CSS_SELECTOR, ".active > .nav-link").click()
    self.driver.find_element(By.LINK_TEXT, "Contact").click()
    self.driver.find_element(By.CSS_SELECTOR, "#exampleModal .btn-secondary").click()
    self.driver.find_element(By.LINK_TEXT, "About us").click()
    self.driver.find_element(By.CSS_SELECTOR, ".vjs-big-play-button > .vjs-icon-placeholder").click()
    self.driver.find_element(By.CSS_SELECTOR, ".vjs-progress-control").click()
    self.driver.find_element(By.CSS_SELECTOR, "#videoModal .btn").click()
    self.driver.find_element(By.ID, "cartur").click()
    self.driver.find_element(By.ID, "login2").click()
    element = self.driver.find_element(By.ID, "login2")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#logInModal span").click()
    self.driver.find_element(By.ID, "signin2").click()
    self.driver.find_element(By.CSS_SELECTOR, "#signInModal span").click()
    self.driver.find_element(By.ID, "nava").click()
  
